version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/source
    depends_on:
     - mysql
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD:
